// e005-solid-supertokens/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Router, Route } from "@solidjs/router";

import "./index.css";
import Auth from "./Auth";
import Dashboard from "./Dashboard";

const root = document.getElementById("root");

render(
  () => (
    <Router>
      <Route path="/dashboard" component={Dashboard} />
      <Route path="/" component={Auth} />
    </Router>
  ),
  root!
);

// e003-react-web-components/demos/react-demo/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import {
  createBrowserRouter,
  RouterProvider,
  useNavigate,
} from "react-router-dom";
import webComponents from "./components/solid-web-components.es";

const Dashboard = () => {
  const navigate = useNavigate();
  webComponents.registerDashboard(navigate);
  return <c-dashboard />;
};

const EmailPassword = () => {
  const navigate = useNavigate();
  webComponents.registerEmailPassword(navigate);
  return <c-email-password />;
};

const router = createBrowserRouter([
  {
    path: "/",
    element: <EmailPassword />,
  },
  {
    path: "/dashboard",
    element: <Dashboard />,
  },
]);

const App = () => {
  console.log("app");

  return (
    <React.StrictMode>
      <RouterProvider router={router} />
    </React.StrictMode>
  );
};

ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
